on : push
name : great
jobs : 
   build :
     runs-on : hi
     strategy :
       matrix :
         hi : [ 14,16 ]
     steps :
       - uses : action/setup-node@v4
         with :
          node-version : ${{ matrix.node }}
       

   
